### ISSUE TITLE
[BUG] Ore Spawners Disappearing

### ISSUE THREAD

**Issue by BrahmjotSingh0** [RKAbdul/OreSpawners#10]
This happens lots of people complaint about it
They said when they break it sometimes it disappeared . also i have noticed it.
We are using auto inventory and even if players inventory is not full it doesn't adds to inventory it disappears.
Try to resolve this thank you 👍

**Comment by RKAbdul** [comment]
From what i have tested and seen.
This bug is still unknown
I haven't seen it anywhere, neither on my own server.

Can you tell us which AutoInv plugin you use?

**Comment by RKAbdul** [comment]
Closed due to unkown bug
