### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by thinh2118** [RKAbdul/OreSpawners#11]
version 0.5.1 stacking has bugs, you can stacking item.

**Comment by thinh2118** [comment]
you can use item in gmc and stacking them.

**Comment by RKAbdul** [comment]
I have looked carefully and I don't see a why this bug is occurring.
Can you kindly, come with a small video proof
So we can see, how actually the bug is

**Comment by RKAbdul** [comment]
Fixed in 0.5.2 thanks.
