### ISSUE TITLE
Bug stacking

### ISSUE THREAD

**Issue by thinh2118** [RKAbdul/OreSpawners#12]
i cant stacking ore spawner.

**Comment by thinh2118** [comment]
plugin send mess limit but my ore spawner is level 1

**Comment by RKAbdul** [comment]
Hey, sorry about that!
I got to know the bug as soon as i released 0.5.2, so i have edited the release and posses fix your bug.
Incase you still get it, please open the issue again!

Edit: download the latest version from 0.5.2 release!

**Comment by thinh2118** [comment]
it still bug

**Comment by thinh2118** [comment]
i cant stacking

**Comment by RKAbdul** [comment]
Hey i have edited the release 0.5.2, download the latest plugin file from there!
Thanks
