### ISSUE TITLE
Stacking can give unlimited spawners

### ISSUE THREAD

**Issue by BrahmjotSingh0** [RKAbdul/OreSpawners#13]
Ik it looks weird but if u have a orespawner and terracotta u can stack terracota to spawners and get unlimited spawners after breaking them.
Make it so terracotta can't stack with orespawners.
If u have problem understanding it see
https://youtu.be/voV9e2xFpaU
Thank u !!

**Comment by RKAbdul** [comment]
Succesfully fixed in 0.5.2 edit release.
Thanks
