### ISSUE TITLE
[SUGGESTION] Take Block In Gamemode C Can Use

### ISSUE THREAD

**Issue by thinh2118** [RKAbdul/OreSpawners#2]
Take Block In Gamemode C Can Use

**Comment by RKAbdul** [comment]
There is nothing much we can do in that, hence it's the block's id on what OreSpawners acts.
We may still try to fix that to only by command in future

**Comment by thinh2118** [comment]
i think you can use nbt or tile to do that

**Comment by RKAbdul** [comment]
This issue is fixed in lates release 0.5
